// Generated by CoffeeScript 2.7.0
(function() {
  var HeyJson, fetchJson;

  fetchJson = require('./helper-fetcher.js');

  HeyJson = class HeyJson {
    constructor(hey = {}) {
      this.runFetch = this.runFetch.bind(this);
      this.hey = hey;
    }

    async runFetch(url) {
      var e, f;
      try {
        f = (await fetchJson(url));
        return f;
      } catch (error) {
        e = error;
        console.log(e);
        return "error fetching json in runFetch method";
      }
    }

  };

  module.exports = HeyJson;

}).call(this);
