// Generated by CoffeeScript 2.7.0
(function() {
  var HeyJson, fetchJson;

  fetchJson = require('./fetcher.js');

  HeyJson = class HeyJson {
    constructor(hey = {}) {
      this.runName = this.runName.bind(this);
      this.runFetch = this.runFetch.bind(this);
      this.runMsg = this.runMsg.bind(this);
      this.hey = hey;
    }

    runName() {
      return this.hey;
    }

    async runFetch(url) {
      var e, f;
      try {
        f = (await fetchJson(url));
        return f;
      } catch (error) {
        e = error;
        console.log(e);
        return "error fetching json in runFetch method";
      }
    }

    runMsg() {
      var msg;
      msg = "hello there";
      return msg;
    }

  };

  module.exports = HeyJson;

}).call(this);
